// Default bot character file for Q3 botlib backport to Quake II.
// Loaded by BotLoadCharacter() via be_ai_char.c.
//
// Format: skill <level> { <index> <value> ... }
//
// Uses chars.h index numbers.  See botfiles/chars.h for full list.
#include "chars.h"

// Skill level 1 (beginner)
skill 1
{
    CHARACTERISTIC_NAME                "DefaultBot"
    CHARACTERISTIC_GENDER              "male"
    CHARACTERISTIC_ATTACK_SKILL        0.2
    CHARACTERISTIC_WEAPONWEIGHTS       "bots/default_w.c"
    CHARACTERISTIC_VIEW_FACTOR         0.5
    CHARACTERISTIC_VIEW_MAXCHANGE      90
    CHARACTERISTIC_REACTIONTIME        1.5
    CHARACTERISTIC_AIM_ACCURACY        0.3
    CHARACTERISTIC_AIM_SKILL           0.2
    CHARACTERISTIC_CHAT_FILE           "bots/default.c"
    CHARACTERISTIC_CHAT_NAME           "defaultbot"
    CHARACTERISTIC_CHAT_CPM            150
    CHARACTERISTIC_CHAT_INSULT         0.1
    CHARACTERISTIC_CHAT_MISC           0.1
    CHARACTERISTIC_CHAT_STARTENDLEVEL  0.1
    CHARACTERISTIC_CHAT_ENTEREXITGAME  0.1
    CHARACTERISTIC_CHAT_KILL           0.1
    CHARACTERISTIC_CHAT_DEATH          0.1
    CHARACTERISTIC_CHAT_ENEMYSUICIDE   0.1
    CHARACTERISTIC_CHAT_HITTALKING     0.1
    CHARACTERISTIC_CHAT_HITNODEATH     0.1
    CHARACTERISTIC_CHAT_HITNOKILL      0.1
    CHARACTERISTIC_CHAT_RANDOM         0.1
    CHARACTERISTIC_CHAT_REPLY          0.2
    CHARACTERISTIC_CROUCHER            0.2
    CHARACTERISTIC_JUMPER              0.3
    CHARACTERISTIC_WEAPONJUMPING       0.0
    CHARACTERISTIC_ITEMWEIGHTS         "bots/default_i.c"
    CHARACTERISTIC_AGGRESSION          0.3
    CHARACTERISTIC_SELFPRESERVATION    0.7
    CHARACTERISTIC_CAMPER              0.2
    CHARACTERISTIC_EASY_FRAGGER        0.5
    CHARACTERISTIC_ALERTNESS           0.3
    CHARACTERISTIC_FIRETHROTTLE        0.8
    CHARACTERISTIC_WALKER              0
}

// Skill level 2
skill 2
{
    CHARACTERISTIC_NAME                "DefaultBot"
    CHARACTERISTIC_GENDER              "male"
    CHARACTERISTIC_ATTACK_SKILL        0.4
    CHARACTERISTIC_WEAPONWEIGHTS       "bots/default_w.c"
    CHARACTERISTIC_VIEW_FACTOR         0.6
    CHARACTERISTIC_VIEW_MAXCHANGE      120
    CHARACTERISTIC_REACTIONTIME        1.0
    CHARACTERISTIC_AIM_ACCURACY        0.5
    CHARACTERISTIC_AIM_SKILL           0.4
    CHARACTERISTIC_CHAT_FILE           "bots/default.c"
    CHARACTERISTIC_CHAT_NAME           "defaultbot"
    CHARACTERISTIC_CHAT_CPM            150
    CHARACTERISTIC_CHAT_INSULT         0.2
    CHARACTERISTIC_CHAT_MISC           0.2
    CHARACTERISTIC_CHAT_STARTENDLEVEL  0.2
    CHARACTERISTIC_CHAT_ENTEREXITGAME  0.2
    CHARACTERISTIC_CHAT_KILL           0.2
    CHARACTERISTIC_CHAT_DEATH          0.2
    CHARACTERISTIC_CHAT_ENEMYSUICIDE   0.2
    CHARACTERISTIC_CHAT_HITTALKING     0.2
    CHARACTERISTIC_CHAT_HITNODEATH     0.2
    CHARACTERISTIC_CHAT_HITNOKILL      0.2
    CHARACTERISTIC_CHAT_RANDOM         0.2
    CHARACTERISTIC_CHAT_REPLY          0.3
    CHARACTERISTIC_CROUCHER            0.2
    CHARACTERISTIC_JUMPER              0.4
    CHARACTERISTIC_WEAPONJUMPING       0.2
    CHARACTERISTIC_ITEMWEIGHTS         "bots/default_i.c"
    CHARACTERISTIC_AGGRESSION          0.5
    CHARACTERISTIC_SELFPRESERVATION    0.5
    CHARACTERISTIC_CAMPER              0.1
    CHARACTERISTIC_EASY_FRAGGER        0.5
    CHARACTERISTIC_ALERTNESS           0.5
    CHARACTERISTIC_FIRETHROTTLE        0.7
    CHARACTERISTIC_WALKER              0
}

// Skill level 3
skill 3
{
    CHARACTERISTIC_NAME                "DefaultBot"
    CHARACTERISTIC_GENDER              "male"
    CHARACTERISTIC_ATTACK_SKILL        0.6
    CHARACTERISTIC_WEAPONWEIGHTS       "bots/default_w.c"
    CHARACTERISTIC_VIEW_FACTOR         0.7
    CHARACTERISTIC_VIEW_MAXCHANGE      150
    CHARACTERISTIC_REACTIONTIME        0.7
    CHARACTERISTIC_AIM_ACCURACY        0.65
    CHARACTERISTIC_AIM_SKILL           0.6
    CHARACTERISTIC_CHAT_FILE           "bots/default.c"
    CHARACTERISTIC_CHAT_NAME           "defaultbot"
    CHARACTERISTIC_CHAT_CPM            150
    CHARACTERISTIC_CHAT_INSULT         0.3
    CHARACTERISTIC_CHAT_MISC           0.3
    CHARACTERISTIC_CHAT_STARTENDLEVEL  0.3
    CHARACTERISTIC_CHAT_ENTEREXITGAME  0.3
    CHARACTERISTIC_CHAT_KILL           0.3
    CHARACTERISTIC_CHAT_DEATH          0.3
    CHARACTERISTIC_CHAT_ENEMYSUICIDE   0.3
    CHARACTERISTIC_CHAT_HITTALKING     0.3
    CHARACTERISTIC_CHAT_HITNODEATH     0.3
    CHARACTERISTIC_CHAT_HITNOKILL      0.3
    CHARACTERISTIC_CHAT_RANDOM         0.3
    CHARACTERISTIC_CHAT_REPLY          0.4
    CHARACTERISTIC_CROUCHER            0.3
    CHARACTERISTIC_JUMPER              0.5
    CHARACTERISTIC_WEAPONJUMPING       0.5
    CHARACTERISTIC_ITEMWEIGHTS         "bots/default_i.c"
    CHARACTERISTIC_AGGRESSION          0.6
    CHARACTERISTIC_SELFPRESERVATION    0.4
    CHARACTERISTIC_CAMPER              0.1
    CHARACTERISTIC_EASY_FRAGGER        0.5
    CHARACTERISTIC_ALERTNESS           0.6
    CHARACTERISTIC_FIRETHROTTLE        0.6
    CHARACTERISTIC_WALKER              0
}

// Skill level 4
skill 4
{
    CHARACTERISTIC_NAME                "DefaultBot"
    CHARACTERISTIC_GENDER              "male"
    CHARACTERISTIC_ATTACK_SKILL        0.8
    CHARACTERISTIC_WEAPONWEIGHTS       "bots/default_w.c"
    CHARACTERISTIC_VIEW_FACTOR         0.8
    CHARACTERISTIC_VIEW_MAXCHANGE      180
    CHARACTERISTIC_REACTIONTIME        0.4
    CHARACTERISTIC_AIM_ACCURACY        0.8
    CHARACTERISTIC_AIM_SKILL           0.8
    CHARACTERISTIC_CHAT_FILE           "bots/default.c"
    CHARACTERISTIC_CHAT_NAME           "defaultbot"
    CHARACTERISTIC_CHAT_CPM            150
    CHARACTERISTIC_CHAT_INSULT         0.4
    CHARACTERISTIC_CHAT_MISC           0.4
    CHARACTERISTIC_CHAT_STARTENDLEVEL  0.4
    CHARACTERISTIC_CHAT_ENTEREXITGAME  0.4
    CHARACTERISTIC_CHAT_KILL           0.4
    CHARACTERISTIC_CHAT_DEATH          0.4
    CHARACTERISTIC_CHAT_ENEMYSUICIDE   0.4
    CHARACTERISTIC_CHAT_HITTALKING     0.4
    CHARACTERISTIC_CHAT_HITNODEATH     0.4
    CHARACTERISTIC_CHAT_HITNOKILL      0.4
    CHARACTERISTIC_CHAT_RANDOM         0.4
    CHARACTERISTIC_CHAT_REPLY          0.5
    CHARACTERISTIC_CROUCHER            0.4
    CHARACTERISTIC_JUMPER              0.6
    CHARACTERISTIC_WEAPONJUMPING       0.7
    CHARACTERISTIC_ITEMWEIGHTS         "bots/default_i.c"
    CHARACTERISTIC_AGGRESSION          0.7
    CHARACTERISTIC_SELFPRESERVATION    0.3
    CHARACTERISTIC_CAMPER              0.1
    CHARACTERISTIC_EASY_FRAGGER        0.6
    CHARACTERISTIC_ALERTNESS           0.8
    CHARACTERISTIC_FIRETHROTTLE        0.5
    CHARACTERISTIC_WALKER              0
}

// Skill level 5 (expert)
skill 5
{
    CHARACTERISTIC_NAME                "DefaultBot"
    CHARACTERISTIC_GENDER              "male"
    CHARACTERISTIC_ATTACK_SKILL        0.95
    CHARACTERISTIC_WEAPONWEIGHTS       "bots/default_w.c"
    CHARACTERISTIC_VIEW_FACTOR         0.95
    CHARACTERISTIC_VIEW_MAXCHANGE      360
    CHARACTERISTIC_REACTIONTIME        0.2
    CHARACTERISTIC_AIM_ACCURACY        0.95
    CHARACTERISTIC_AIM_SKILL           0.95
    CHARACTERISTIC_CHAT_FILE           "bots/default.c"
    CHARACTERISTIC_CHAT_NAME           "defaultbot"
    CHARACTERISTIC_CHAT_CPM            150
    CHARACTERISTIC_CHAT_INSULT         0.5
    CHARACTERISTIC_CHAT_MISC           0.5
    CHARACTERISTIC_CHAT_STARTENDLEVEL  0.5
    CHARACTERISTIC_CHAT_ENTEREXITGAME  0.5
    CHARACTERISTIC_CHAT_KILL           0.5
    CHARACTERISTIC_CHAT_DEATH          0.5
    CHARACTERISTIC_CHAT_ENEMYSUICIDE   0.5
    CHARACTERISTIC_CHAT_HITTALKING     0.5
    CHARACTERISTIC_CHAT_HITNODEATH     0.5
    CHARACTERISTIC_CHAT_HITNOKILL      0.5
    CHARACTERISTIC_CHAT_RANDOM         0.5
    CHARACTERISTIC_CHAT_REPLY          0.6
    CHARACTERISTIC_CROUCHER            0.5
    CHARACTERISTIC_JUMPER              0.7
    CHARACTERISTIC_WEAPONJUMPING       1.0
    CHARACTERISTIC_ITEMWEIGHTS         "bots/default_i.c"
    CHARACTERISTIC_AGGRESSION          0.85
    CHARACTERISTIC_SELFPRESERVATION    0.2
    CHARACTERISTIC_CAMPER              0.05
    CHARACTERISTIC_EASY_FRAGGER        0.7
    CHARACTERISTIC_ALERTNESS           0.95
    CHARACTERISTIC_FIRETHROTTLE        0.4
    CHARACTERISTIC_WALKER              0
}
