//===========================================================================
// I hate header files...
// Notes:			If there's anything wrong in here, blame Todd. =)
//===========================================================================

#include "chars.h"

skill 1
{
	CHARACTERISTIC_NAME							"Xian"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/xian_w.c"
	CHARACTERISTIC_CHAT_FILE					"bots/xian_t.c"
	CHARACTERISTIC_CHAT_NAME					"xian"
	CHARACTERISTIC_ITEMWEIGHTS					"bots/xian_i.c"

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.1
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.1
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.1
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.1
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.1
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.1
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.6
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.1
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.1
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.1
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.1
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.1

	CHARACTERISTIC_CHAT_INSULT					0.4
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.1
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.35
}

skill 4
{
	CHARACTERISTIC_NAME							"Xian"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.75
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/xian_w.c"
	CHARACTERISTIC_AIM_SKILL					0.75
	CHARACTERISTIC_AIM_ACCURACY					0.75
	CHARACTERISTIC_VIEW_FACTOR					0.65
	CHARACTERISTIC_VIEW_MAXCHANGE				180
	CHARACTERISTIC_REACTIONTIME					0.5

	CHARACTERISTIC_CHAT_FILE					"bots/xian_t.c"
	CHARACTERISTIC_CHAT_NAME					"xian"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.4
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.05
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.25

	CHARACTERISTIC_CROUCHER						0.25
	CHARACTERISTIC_JUMPER						0.35
	CHARACTERISTIC_WEAPONJUMPING				0.80
	CHARACTERISTIC_GRAPPLE_USER					0.05

	CHARACTERISTIC_ITEMWEIGHTS					"bots/xian_i.c"
	CHARACTERISTIC_AGGRESSION					0.75
	CHARACTERISTIC_SELFPRESERVATION				0.95
	CHARACTERISTIC_VENGEFULNESS					0.95
	CHARACTERISTIC_CAMPER						1.0

	CHARACTERISTIC_EASY_FRAGGER					0.05
	CHARACTERISTIC_ALERTNESS					0.95

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.6
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.6
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.6
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.6
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.6
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.6
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.8
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.6
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.6
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.6
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.6
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.6

	CHARACTERISTIC_FIRETHROTTLE					0.8
}

skill 5
{
	CHARACTERISTIC_NAME							"Xian"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.75
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/xian_w.c"
	CHARACTERISTIC_AIM_SKILL					0.75
	CHARACTERISTIC_AIM_ACCURACY					0.75
	CHARACTERISTIC_VIEW_FACTOR					0.65
	CHARACTERISTIC_VIEW_MAXCHANGE				180
	CHARACTERISTIC_REACTIONTIME					0.5

	CHARACTERISTIC_CHAT_FILE					"bots/xian_t.c"
	CHARACTERISTIC_CHAT_NAME					"xian"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.4
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.05
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.25

	CHARACTERISTIC_CROUCHER						0.25
	CHARACTERISTIC_JUMPER						0.35
	CHARACTERISTIC_WEAPONJUMPING				0.80
	CHARACTERISTIC_GRAPPLE_USER					0.05

	CHARACTERISTIC_ITEMWEIGHTS					"bots/xian_i.c"
	CHARACTERISTIC_AGGRESSION					0.75
	CHARACTERISTIC_SELFPRESERVATION				0.95
	CHARACTERISTIC_VENGEFULNESS					0.95
	CHARACTERISTIC_CAMPER						1.0

	CHARACTERISTIC_EASY_FRAGGER					0.05
	CHARACTERISTIC_ALERTNESS					0.95

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.6
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.6
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.6
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.6
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.6
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.6
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.8
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.6
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.6
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.6
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.6
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.6

	CHARACTERISTIC_FIRETHROTTLE					0.8
}