//===========================================================================
//
// Name:			crash_c.c
// Function:		crash, rank 2
// Programmer:		MrElusive (MrElusive@idsoftware.com)
// version:			1
// Tab Size:		4 (real tabs)
//===========================================================================

#include "chars.h"

skill 1
{
	CHARACTERISTIC_NAME							"Crash"
	CHARACTERISTIC_GENDER						"female"
	CHARACTERISTIC_ATTACK_SKILL					0.2
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/crash_w.c"
	CHARACTERISTIC_AIM_SKILL					0.2
	CHARACTERISTIC_AIM_ACCURACY					0.2
	CHARACTERISTIC_VIEW_FACTOR					0.2
	CHARACTERISTIC_VIEW_MAXCHANGE				180
	CHARACTERISTIC_REACTIONTIME					5.0

	CHARACTERISTIC_CHAT_FILE					"bots/crash_t.c"
	CHARACTERISTIC_CHAT_NAME					"crash"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.4
	CHARACTERISTIC_CHAT_MISC					1.0
	CHARACTERISTIC_CHAT_STARTENDLEVEL			1.0
	CHARACTERISTIC_CHAT_ENTEREXITGAME			1.0
	CHARACTERISTIC_CHAT_KILL					1.0
	CHARACTERISTIC_CHAT_DEATH					1.0
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			1.0
	CHARACTERISTIC_CHAT_HITTALKING				1.0
	CHARACTERISTIC_CHAT_HITNODEATH				1.0
	CHARACTERISTIC_CHAT_HITNOKILL				1.0
	CHARACTERISTIC_CHAT_RANDOM					1.0
	CHARACTERISTIC_CHAT_REPLY					1.0

	CHARACTERISTIC_CROUCHER						0.0
	CHARACTERISTIC_JUMPER						0.0
	CHARACTERISTIC_WEAPONJUMPING				0.0
	CHARACTERISTIC_GRAPPLE_USER					0.0
	CHARACTERISTIC_WALKER						1.0

	CHARACTERISTIC_ITEMWEIGHTS					"bots/crash_i.c"
	CHARACTERISTIC_AGGRESSION					0.0
	CHARACTERISTIC_SELFPRESERVATION				0.0
	CHARACTERISTIC_VENGEFULNESS					0.0
	CHARACTERISTIC_CAMPER						0.0

	CHARACTERISTIC_EASY_FRAGGER					0.0
	CHARACTERISTIC_ALERTNESS					0.0
	CHARACTERISTIC_FIRETHROTTLE					0.1
}

skill 4
{
	CHARACTERISTIC_NAME							"Crash"
	CHARACTERISTIC_GENDER						"female"
	CHARACTERISTIC_ATTACK_SKILL					0.7
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/crash_w.c"
	CHARACTERISTIC_AIM_SKILL					0.7
	CHARACTERISTIC_AIM_ACCURACY					0.7
	CHARACTERISTIC_VIEW_FACTOR					0.7
	CHARACTERISTIC_VIEW_MAXCHANGE				180
	CHARACTERISTIC_REACTIONTIME					2.5

	CHARACTERISTIC_CHAT_FILE					"bots/crash_t.c"
	CHARACTERISTIC_CHAT_NAME					"crash"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.4
	CHARACTERISTIC_CHAT_MISC					1.0
	CHARACTERISTIC_CHAT_STARTENDLEVEL			1.0
	CHARACTERISTIC_CHAT_ENTEREXITGAME			1.0
	CHARACTERISTIC_CHAT_KILL					1.0
	CHARACTERISTIC_CHAT_DEATH					1.0
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			1.0
	CHARACTERISTIC_CHAT_HITTALKING				1.0
	CHARACTERISTIC_CHAT_HITNODEATH				1.0
	CHARACTERISTIC_CHAT_HITNOKILL				1.0
	CHARACTERISTIC_CHAT_RANDOM					1.0
	CHARACTERISTIC_CHAT_REPLY					1.0

	CHARACTERISTIC_CROUCHER						0.0
	CHARACTERISTIC_JUMPER						0.0
	CHARACTERISTIC_WEAPONJUMPING				0.0
	CHARACTERISTIC_GRAPPLE_USER					0.0
	CHARACTERISTIC_WALKER						1.0

	CHARACTERISTIC_ITEMWEIGHTS					"bots/crash_i.c"
	CHARACTERISTIC_AGGRESSION					0.7
	CHARACTERISTIC_SELFPRESERVATION				0.7
	CHARACTERISTIC_VENGEFULNESS					0.7
	CHARACTERISTIC_CAMPER						0.7

	CHARACTERISTIC_EASY_FRAGGER					0.0
	CHARACTERISTIC_ALERTNESS					0.7
	CHARACTERISTIC_FIRETHROTTLE					0.8
}

skill 5
{
	CHARACTERISTIC_NAME							"Crash"
	CHARACTERISTIC_GENDER						"female"
	CHARACTERISTIC_ATTACK_SKILL					1.0
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/crash_w.c"
	CHARACTERISTIC_AIM_SKILL					1.0
	CHARACTERISTIC_AIM_ACCURACY					1.0
	CHARACTERISTIC_VIEW_FACTOR					1.0
	CHARACTERISTIC_VIEW_MAXCHANGE				360
	CHARACTERISTIC_REACTIONTIME					0.0

	CHARACTERISTIC_CHAT_FILE					"bots/crash_t.c"
	CHARACTERISTIC_CHAT_NAME					"crash"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.4
	CHARACTERISTIC_CHAT_MISC					1.0
	CHARACTERISTIC_CHAT_STARTENDLEVEL			1.0
	CHARACTERISTIC_CHAT_ENTEREXITGAME			1.0
	CHARACTERISTIC_CHAT_KILL					1.0
	CHARACTERISTIC_CHAT_DEATH					1.0
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			1.0
	CHARACTERISTIC_CHAT_HITTALKING				1.0
	CHARACTERISTIC_CHAT_HITNODEATH				1.0
	CHARACTERISTIC_CHAT_HITNOKILL				1.0
	CHARACTERISTIC_CHAT_RANDOM					1.0
	CHARACTERISTIC_CHAT_REPLY					1.0

	CHARACTERISTIC_CROUCHER						0.0
	CHARACTERISTIC_JUMPER						1.0
	CHARACTERISTIC_WEAPONJUMPING				1.0
	CHARACTERISTIC_GRAPPLE_USER					0.0

	CHARACTERISTIC_ITEMWEIGHTS					"bots/crash_i.c"
	CHARACTERISTIC_AGGRESSION					1.0
	CHARACTERISTIC_SELFPRESERVATION				1.0
	CHARACTERISTIC_VENGEFULNESS					1.0
	CHARACTERISTIC_CAMPER						1.0

	CHARACTERISTIC_EASY_FRAGGER					1.0
	CHARACTERISTIC_ALERTNESS					1.0
	CHARACTERISTIC_FIRETHROTTLE					1.0
}
