// Default bot character file for Q3 botlib backport to Quake II.
// Loaded by BotLoadCharacter() via be_ai_char.c.
//
// Format: skill <level> { <index> <value> ... }
//
// Uses chars.h index numbers.  See botfiles/chars.h for full list.
//
// Every characteristic in chars.h is defined here: besides being the default
// bot, this file supplies whatever another character file leaves out
// (BotLoadCharacterSkill merges it in), and a characteristic nobody defines
// reads as 0.
//
// Per-weapon aim (AIM_ACCURACY_*/AIM_SKILL_*): BotAimAtEnemy uses these
// instead of the general AIM_ACCURACY/AIM_SKILL for the weapon in hand. The
// names are Q3's; botlib/ai_q2_compat.h pairs them with Q2 weapons
// (MACHINEGUN = Machinegun, SHOTGUN = Shotgun, LIGHTNING = Chaingun,
// PLASMAGUN = HyperBlaster, GRENADELAUNCHER, ROCKETLAUNCHER, RAILGUN, BFG10K
// as named). Here they equal each skill level's general values; the Blaster,
// Super Shotgun and hand grenades always use the general ones.
#include "chars.h"

// Skill level 1 (beginner)
skill 1
{
    CHARACTERISTIC_NAME                "DefaultBot"
    CHARACTERISTIC_GENDER              "male"
    CHARACTERISTIC_ATTACK_SKILL        0.2
    CHARACTERISTIC_WEAPONWEIGHTS       "bots/default_w.c"
    CHARACTERISTIC_VIEW_FACTOR         0.5
    CHARACTERISTIC_VIEW_MAXCHANGE      90
    CHARACTERISTIC_REACTIONTIME        1.5
    CHARACTERISTIC_AIM_ACCURACY        0.3
    CHARACTERISTIC_AIM_SKILL           0.2
    CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN      0.3
    CHARACTERISTIC_AIM_ACCURACY_SHOTGUN         0.3
    CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER  0.3
    CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER 0.3
    CHARACTERISTIC_AIM_ACCURACY_LIGHTNING       0.3
    CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN       0.3
    CHARACTERISTIC_AIM_ACCURACY_RAILGUN         0.3
    CHARACTERISTIC_AIM_ACCURACY_BFG10K          0.3
    CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER     0.2
    CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER    0.2
    CHARACTERISTIC_AIM_SKILL_PLASMAGUN          0.2
    CHARACTERISTIC_AIM_SKILL_BFG10K             0.2
    CHARACTERISTIC_CHAT_FILE           "bots/default.c"
    CHARACTERISTIC_CHAT_NAME           "defaultbot"
    CHARACTERISTIC_CHAT_CPM            150
    CHARACTERISTIC_CHAT_INSULT         0.1
    CHARACTERISTIC_CHAT_MISC           0.1
    CHARACTERISTIC_CHAT_STARTENDLEVEL  0.1
    CHARACTERISTIC_CHAT_ENTEREXITGAME  0.1
    CHARACTERISTIC_CHAT_KILL           0.1
    CHARACTERISTIC_CHAT_DEATH          0.1
    CHARACTERISTIC_CHAT_ENEMYSUICIDE   0.1
    CHARACTERISTIC_CHAT_HITTALKING     0.1
    CHARACTERISTIC_CHAT_HITNODEATH     0.1
    CHARACTERISTIC_CHAT_HITNOKILL      0.1
    CHARACTERISTIC_CHAT_RANDOM         0.1
    CHARACTERISTIC_CHAT_REPLY          0.2
    CHARACTERISTIC_CROUCHER            0.2
    CHARACTERISTIC_JUMPER              0.3
    CHARACTERISTIC_WEAPONJUMPING       0.0
    CHARACTERISTIC_GRAPPLE_USER                 0.5
    CHARACTERISTIC_ITEMWEIGHTS         "bots/default_i.c"
    CHARACTERISTIC_AGGRESSION          0.3
    CHARACTERISTIC_SELFPRESERVATION    0.7
    CHARACTERISTIC_VENGEFULNESS                 0.25
    CHARACTERISTIC_CAMPER              0.2
    CHARACTERISTIC_EASY_FRAGGER        0.5
    CHARACTERISTIC_ALERTNESS           0.3
    CHARACTERISTIC_FIRETHROTTLE        0.8
    CHARACTERISTIC_WALKER              0
}

// Skill level 2
skill 2
{
    CHARACTERISTIC_NAME                "DefaultBot"
    CHARACTERISTIC_GENDER              "male"
    CHARACTERISTIC_ATTACK_SKILL        0.4
    CHARACTERISTIC_WEAPONWEIGHTS       "bots/default_w.c"
    CHARACTERISTIC_VIEW_FACTOR         0.6
    CHARACTERISTIC_VIEW_MAXCHANGE      120
    CHARACTERISTIC_REACTIONTIME        1.0
    CHARACTERISTIC_AIM_ACCURACY        0.5
    CHARACTERISTIC_AIM_SKILL           0.4
    CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN      0.5
    CHARACTERISTIC_AIM_ACCURACY_SHOTGUN         0.5
    CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER  0.5
    CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER 0.5
    CHARACTERISTIC_AIM_ACCURACY_LIGHTNING       0.5
    CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN       0.5
    CHARACTERISTIC_AIM_ACCURACY_RAILGUN         0.5
    CHARACTERISTIC_AIM_ACCURACY_BFG10K          0.5
    CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER     0.4
    CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER    0.4
    CHARACTERISTIC_AIM_SKILL_PLASMAGUN          0.4
    CHARACTERISTIC_AIM_SKILL_BFG10K             0.4
    CHARACTERISTIC_CHAT_FILE           "bots/default.c"
    CHARACTERISTIC_CHAT_NAME           "defaultbot"
    CHARACTERISTIC_CHAT_CPM            150
    CHARACTERISTIC_CHAT_INSULT         0.2
    CHARACTERISTIC_CHAT_MISC           0.2
    CHARACTERISTIC_CHAT_STARTENDLEVEL  0.2
    CHARACTERISTIC_CHAT_ENTEREXITGAME  0.2
    CHARACTERISTIC_CHAT_KILL           0.2
    CHARACTERISTIC_CHAT_DEATH          0.2
    CHARACTERISTIC_CHAT_ENEMYSUICIDE   0.2
    CHARACTERISTIC_CHAT_HITTALKING     0.2
    CHARACTERISTIC_CHAT_HITNODEATH     0.2
    CHARACTERISTIC_CHAT_HITNOKILL      0.2
    CHARACTERISTIC_CHAT_RANDOM         0.2
    CHARACTERISTIC_CHAT_REPLY          0.3
    CHARACTERISTIC_CROUCHER            0.2
    CHARACTERISTIC_JUMPER              0.4
    CHARACTERISTIC_WEAPONJUMPING       0.2
    CHARACTERISTIC_GRAPPLE_USER                 0.67
    CHARACTERISTIC_ITEMWEIGHTS         "bots/default_i.c"
    CHARACTERISTIC_AGGRESSION          0.5
    CHARACTERISTIC_SELFPRESERVATION    0.5
    CHARACTERISTIC_VENGEFULNESS                 0.5
    CHARACTERISTIC_CAMPER              0.1
    CHARACTERISTIC_EASY_FRAGGER        0.5
    CHARACTERISTIC_ALERTNESS           0.5
    CHARACTERISTIC_FIRETHROTTLE        0.7
    CHARACTERISTIC_WALKER              0
}

// Skill level 3
skill 3
{
    CHARACTERISTIC_NAME                "DefaultBot"
    CHARACTERISTIC_GENDER              "male"
    CHARACTERISTIC_ATTACK_SKILL        0.6
    CHARACTERISTIC_WEAPONWEIGHTS       "bots/default_w.c"
    CHARACTERISTIC_VIEW_FACTOR         0.7
    CHARACTERISTIC_VIEW_MAXCHANGE      150
    CHARACTERISTIC_REACTIONTIME        0.7
    CHARACTERISTIC_AIM_ACCURACY        0.65
    CHARACTERISTIC_AIM_SKILL           0.6
    CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN      0.65
    CHARACTERISTIC_AIM_ACCURACY_SHOTGUN         0.65
    CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER  0.65
    CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER 0.65
    CHARACTERISTIC_AIM_ACCURACY_LIGHTNING       0.65
    CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN       0.65
    CHARACTERISTIC_AIM_ACCURACY_RAILGUN         0.65
    CHARACTERISTIC_AIM_ACCURACY_BFG10K          0.65
    CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER     0.6
    CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER    0.6
    CHARACTERISTIC_AIM_SKILL_PLASMAGUN          0.6
    CHARACTERISTIC_AIM_SKILL_BFG10K             0.6
    CHARACTERISTIC_CHAT_FILE           "bots/default.c"
    CHARACTERISTIC_CHAT_NAME           "defaultbot"
    CHARACTERISTIC_CHAT_CPM            150
    CHARACTERISTIC_CHAT_INSULT         0.3
    CHARACTERISTIC_CHAT_MISC           0.3
    CHARACTERISTIC_CHAT_STARTENDLEVEL  0.3
    CHARACTERISTIC_CHAT_ENTEREXITGAME  0.3
    CHARACTERISTIC_CHAT_KILL           0.3
    CHARACTERISTIC_CHAT_DEATH          0.3
    CHARACTERISTIC_CHAT_ENEMYSUICIDE   0.3
    CHARACTERISTIC_CHAT_HITTALKING     0.3
    CHARACTERISTIC_CHAT_HITNODEATH     0.3
    CHARACTERISTIC_CHAT_HITNOKILL      0.3
    CHARACTERISTIC_CHAT_RANDOM         0.3
    CHARACTERISTIC_CHAT_REPLY          0.4
    CHARACTERISTIC_CROUCHER            0.3
    CHARACTERISTIC_JUMPER              0.5
    CHARACTERISTIC_WEAPONJUMPING       0.5
    CHARACTERISTIC_GRAPPLE_USER                 0.83
    CHARACTERISTIC_ITEMWEIGHTS         "bots/default_i.c"
    CHARACTERISTIC_AGGRESSION          0.6
    CHARACTERISTIC_SELFPRESERVATION    0.4
    CHARACTERISTIC_VENGEFULNESS                 0.75
    CHARACTERISTIC_CAMPER              0.1
    CHARACTERISTIC_EASY_FRAGGER        0.5
    CHARACTERISTIC_ALERTNESS           0.6
    CHARACTERISTIC_FIRETHROTTLE        0.6
    CHARACTERISTIC_WALKER              0
}

// Skill level 4
skill 4
{
    CHARACTERISTIC_NAME                "DefaultBot"
    CHARACTERISTIC_GENDER              "male"
    CHARACTERISTIC_ATTACK_SKILL        0.8
    CHARACTERISTIC_WEAPONWEIGHTS       "bots/default_w.c"
    CHARACTERISTIC_VIEW_FACTOR         0.8
    CHARACTERISTIC_VIEW_MAXCHANGE      180
    CHARACTERISTIC_REACTIONTIME        0.4
    CHARACTERISTIC_AIM_ACCURACY        0.8
    CHARACTERISTIC_AIM_SKILL           0.8
    CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN      0.8
    CHARACTERISTIC_AIM_ACCURACY_SHOTGUN         0.8
    CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER  0.8
    CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER 0.8
    CHARACTERISTIC_AIM_ACCURACY_LIGHTNING       0.8
    CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN       0.8
    CHARACTERISTIC_AIM_ACCURACY_RAILGUN         0.8
    CHARACTERISTIC_AIM_ACCURACY_BFG10K          0.8
    CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER     0.8
    CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER    0.8
    CHARACTERISTIC_AIM_SKILL_PLASMAGUN          0.8
    CHARACTERISTIC_AIM_SKILL_BFG10K             0.8
    CHARACTERISTIC_CHAT_FILE           "bots/default.c"
    CHARACTERISTIC_CHAT_NAME           "defaultbot"
    CHARACTERISTIC_CHAT_CPM            150
    CHARACTERISTIC_CHAT_INSULT         0.4
    CHARACTERISTIC_CHAT_MISC           0.4
    CHARACTERISTIC_CHAT_STARTENDLEVEL  0.4
    CHARACTERISTIC_CHAT_ENTEREXITGAME  0.4
    CHARACTERISTIC_CHAT_KILL           0.4
    CHARACTERISTIC_CHAT_DEATH          0.4
    CHARACTERISTIC_CHAT_ENEMYSUICIDE   0.4
    CHARACTERISTIC_CHAT_HITTALKING     0.4
    CHARACTERISTIC_CHAT_HITNODEATH     0.4
    CHARACTERISTIC_CHAT_HITNOKILL      0.4
    CHARACTERISTIC_CHAT_RANDOM         0.4
    CHARACTERISTIC_CHAT_REPLY          0.5
    CHARACTERISTIC_CROUCHER            0.4
    CHARACTERISTIC_JUMPER              0.6
    CHARACTERISTIC_WEAPONJUMPING       0.7
    CHARACTERISTIC_GRAPPLE_USER                 1.0
    CHARACTERISTIC_ITEMWEIGHTS         "bots/default_i.c"
    CHARACTERISTIC_AGGRESSION          0.7
    CHARACTERISTIC_SELFPRESERVATION    0.3
    CHARACTERISTIC_VENGEFULNESS                 1.0
    CHARACTERISTIC_CAMPER              0.1
    CHARACTERISTIC_EASY_FRAGGER        0.6
    CHARACTERISTIC_ALERTNESS           0.8
    CHARACTERISTIC_FIRETHROTTLE        0.5
    CHARACTERISTIC_WALKER              0
}

// Skill level 5 (expert)
skill 5
{
    CHARACTERISTIC_NAME                "DefaultBot"
    CHARACTERISTIC_GENDER              "male"
    CHARACTERISTIC_ATTACK_SKILL        0.95
    CHARACTERISTIC_WEAPONWEIGHTS       "bots/default_w.c"
    CHARACTERISTIC_VIEW_FACTOR         0.95
    CHARACTERISTIC_VIEW_MAXCHANGE      360
    CHARACTERISTIC_REACTIONTIME        0.2
    CHARACTERISTIC_AIM_ACCURACY        0.95
    CHARACTERISTIC_AIM_SKILL           0.95
    CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN      0.95
    CHARACTERISTIC_AIM_ACCURACY_SHOTGUN         0.95
    CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER  0.95
    CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER 0.95
    CHARACTERISTIC_AIM_ACCURACY_LIGHTNING       0.95
    CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN       0.95
    CHARACTERISTIC_AIM_ACCURACY_RAILGUN         0.95
    CHARACTERISTIC_AIM_ACCURACY_BFG10K          0.95
    CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER     0.95
    CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER    0.95
    CHARACTERISTIC_AIM_SKILL_PLASMAGUN          0.95
    CHARACTERISTIC_AIM_SKILL_BFG10K             0.95
    CHARACTERISTIC_CHAT_FILE           "bots/default.c"
    CHARACTERISTIC_CHAT_NAME           "defaultbot"
    CHARACTERISTIC_CHAT_CPM            150
    CHARACTERISTIC_CHAT_INSULT         0.5
    CHARACTERISTIC_CHAT_MISC           0.5
    CHARACTERISTIC_CHAT_STARTENDLEVEL  0.5
    CHARACTERISTIC_CHAT_ENTEREXITGAME  0.5
    CHARACTERISTIC_CHAT_KILL           0.5
    CHARACTERISTIC_CHAT_DEATH          0.5
    CHARACTERISTIC_CHAT_ENEMYSUICIDE   0.5
    CHARACTERISTIC_CHAT_HITTALKING     0.5
    CHARACTERISTIC_CHAT_HITNODEATH     0.5
    CHARACTERISTIC_CHAT_HITNOKILL      0.5
    CHARACTERISTIC_CHAT_RANDOM         0.5
    CHARACTERISTIC_CHAT_REPLY          0.6
    CHARACTERISTIC_CROUCHER            0.5
    CHARACTERISTIC_JUMPER              0.7
    CHARACTERISTIC_WEAPONJUMPING       1.0
    CHARACTERISTIC_GRAPPLE_USER                 1.0
    CHARACTERISTIC_ITEMWEIGHTS         "bots/default_i.c"
    CHARACTERISTIC_AGGRESSION          0.85
    CHARACTERISTIC_SELFPRESERVATION    0.2
    CHARACTERISTIC_VENGEFULNESS                 1.0
    CHARACTERISTIC_CAMPER              0.05
    CHARACTERISTIC_EASY_FRAGGER        0.7
    CHARACTERISTIC_ALERTNESS           0.95
    CHARACTERISTIC_FIRETHROTTLE        0.4
    CHARACTERISTIC_WALKER              0
}
